CREATE TABLE IF NOT EXISTS ledger_decisions (
    decision_id TEXT PRIMARY KEY,
    game_id TEXT NOT NULL,
    date TEXT NOT NULL,
    sport TEXT NOT NULL,
    league TEXT NOT NULL,
    category TEXT NOT NULL,
    market TEXT NOT NULL,
    selection TEXT NOT NULL,
    odds REAL,
    units REAL NOT NULL,
    confidence REAL NOT NULL,
    luca_score REAL,
    expected_value REAL,
    result TEXT,
    units_won_lost REAL,
    final_score TEXT,
    closing_odds REAL,
    clv REAL,
    module_snapshot TEXT NOT NULL,
    governance_snapshot TEXT NOT NULL,
    audit_status TEXT NOT NULL
);
